### ISSUE TITLE
Make this library a drop in replacement for networkx

### ISSUE THREAD

**Issue by thedrow** [Qiskit/retworkx#248]
### What is the expected enhancement?

Right now I can't use this library since the class names are different from NetworkX and there's no reason they should be.
If the rest of the API matches, I can offer this as an extra in my package.

**Comment by mtreinish** [comment]
Thanks for opening an issue, unfortunately the retworkx api isn't a 1:1 mapping with networkx so it's not a simple drop-in replacement (which is part of why we didn't use the same class names). The big differences are that in retworkx nodes (and edges) are all integer indexed and can only be accessed by this integer id, while in networkx everything is associative.

For example, in networkx you can do something like:

```python
import networkx as nx

graph = nx.MultiDiGraph()
graph.add_node('my_node_a')
graph.add_node('my_node_b')
graph.add_edge('my_node_a', 'my_node_b')
```

while in retworkx it would be something like:

```python
import retworkx as rx

graph = rx.PyDiGraph()
node_a = graph.add_node('my_node_a')
assert node_a == 0
assert graph[0] == 'my_node_a'
node_b = graph.add_node('my_node_b')
assert node_b == 1
assert graph[1] == 'my_node_b'
graph.add_edge(0, 1, None)
```

There are also a lot of subtle differences similar to this. It's not too hard to adapt the usage between the 2, (for example, qiskit terra used to do this with two classes: https://github.com/Qiskit/qiskit-terra/blob/stable/0.14/qiskit/dagcircuit/dagcircuit.py  which would switch based on what's available) but I don't think it'll ever be as simple as just replacing an import to use the faster package if it's installed.

That being said I'm not gonna close this yet because while I don't think we can work towards making the api a drop in replacement for networkx there might be things we can do to make switching between the 2 simpler, so I'll leave this open so we can discuss that.

**Comment by thedrow** [comment]
If I can't drop this library and expect better performance it is going to be a problem for me to use it.
We can create a compatibility shim which adapts the retworkx API to the NetworkX API.

What's the reason between the API differences? Where are they documented?

**Comment by mtreinish** [comment]
There is no documentation on the side-by-side differences with networkx or a migration guide for going from networkx->retworkx. But, that's definitely something we can look at adding to the documentation (and would be a welcome addition and a good outcome for this issue). That being said right now, retworkx doesn't have the full set of features that networkx offers, mainly the algorithms API is only a subset of what networkx has. We've been continually expanding it as users have need for new things. So if there are feature gaps feel free to open another issue on those APIs and we can look at adding them.

A compatibility shim is sort of what I was advocating for in my earlier comment (that's basically what I linked to in the old qiskit-terra code). The big thing you'd need to do is maintain a dict (or other mapping) of node payloads to their node index in retworkx. Do you have example of how you're using networkx that I can look at and I can provide more targeted advice.

The reason for the differences are fundamentally about performance and the rust<->python boundary. The internal data representation of the graph in retworkx (via the petgraph library) are two `Vec`s which are integer indexed. If we wanted to mirror the associative nature of networkx we would could change that internal structure to something that more closely represents a python dict, but then we would need to get a GIL handle and call python to introspect the data every time we did any operation on the graph and also rely on python to hash and do equality checks on the payload which would become the performance bottleneck. The way the graph data structures are handled right now is each node and edge is integer indexed which is simple one time conversion from a python `int` <-> rust `usize` and the actual weight/data payload of a node or edge are kept as a pointer to the raw python objects and retworkx doesn't care what the contents are. This retains flexibility in what gets put on a graph, but still retains fast performance from doing most graph operations natively in rust. 

The only complication is if an algorithm depends on the weights of a node or edge we still need to callback to python to get that in a known type. You can see examples of that in https://retworkx.readthedocs.io/en/stable/stubs/retworkx.lexicographical_topological_sort.html and https://retworkx.readthedocs.io/en/stable/stubs/retworkx.digraph_floyd_warshall_numpy.html

**Comment by thedrow** [comment]
This is an [example](https://github.com/celery/bootsteps/blob/master/bootsteps/blueprint.py#L86) of what I'm currently doing with NetworkX.
I don't really use the associative features of the graph class in NetworkX.

A good start on this issue would be to rename the class names of our graph implementations and ensure that most of the API (design limitations aside) is **exactly** the same.
Same function names, same arguments if possible, etc.

**Comment by mtreinish** [comment]
I've opened #252 to start a guide for existing users of networkx on how it differs from retworkx. What you're asking for with renaming everything in retworkx to exactly mirror networkx's api, unfortunately, I don't think is a realistic outcome here. To rename classes and api functions would be a pretty big breaking change and because retworkx has existing users doing so would be disruptive to those users. I also personally don't feel that using the same names for classes as networkx is a good fit because the behavior of the classes is very different between the 2 libraries. So I think instead documenting the differences and explaining how users can adapt from networkx to retworkx is the best outcome here. The documentation in #252 is a starting point for that, we can continue to expand on that document over time.

When #252 merges it will close this issue, but please feel free to reopen it if there is more to discuss here or there is more work needed. I just marked the PR as fixing this issue because it's the starting point for that documentation to address the concerns.
