### ISSUE TITLE
Cannot subclass from 

### ISSUE THREAD

**Issue by peendebak** [Qiskit/retworkx#275]
### Information

- **retworkx version**: 0.8.0
- **Python version**: 3.8
- **Rust version**: From PyPi
- **Operating system**: Windows

### What is the current behavior?

Subclassing fails the `PyDiGraph` fails. A minimal example:

```
from retworkx import PyDiGraph

class A(DiGraph):
    def __init__(self, ):
        super().__init__()
        
a=A('s')
```
### What is the expected behavior?

One should be able to subclass the PyDiGraph

### Steps to reproduce the problem

See the minimal example above

**Comment by mtreinish** [comment]
I think this is because there is a typo in your example, you're trying to inherit `A` from `DiGraph` but it should be `PyDiGraph`. Does it still fail if you change it to: `class A(PyDiGraph):`?

We actually subclass `PyDiGraph` from python as part of retworkx itself (for backwards compat with older releases), see: https://github.com/Qiskit/retworkx/blob/master/retworkx/__init__.py#L16 so I'd be a bit surprised if this doesn't work.

**Comment by mtreinish** [comment]
I'm going to close this issue as stale. But, please feel free to reopen it if there is more to discuss or you have more details on the issue. Retworkx should support being able to subclass the graph classes and I want to make sure it works.
