### ISSUE TITLE
The result of `graph_greedy_color` is not deterministic

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/retworkx#347]
### What is the expected enhancement?

The result of `graph_greedy_color` is not deterministic as follows.
```python
import retworkx as rx
graph = rx.PyGraph()
graph.add_nodes_from(range(2))
coloring_dict = rx.graph_greedy_color(graph).items()
print(coloring_dict)
```

result:`dict_items([(0, 0), (1, 0)])` or `dict_items([(1, 0), (0, 0)])`.

This is perhaps due to hashmap order of rust.
It might be good to make the result deterministic or write a note in the documentation.

@ikkoham found this.

**Comment by georgios-ts** [comment]
Indeed the order of iterating over a hashmap can be arbitary (https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.iter).
Is an order based on nodes indexes preferred?
We can easily do this by replacing this loop
https://github.com/Qiskit/retworkx/blob/010e0de6b8b475843df8aba511fc5731e386fa01/src/lib.rs#L929-L930
with
```rust
for index in graph.graph.node_indices() {
        let index = index.index();
        out_dict.set_item(index, colors[&index])?;
    }
```
but with a small performance  overhead.
Personally, i would leave it as it is and state this behavior in the documentation.

**Comment by mtreinish** [comment]
@georgios-ts I wonder what the performance of using a `BTreeMap`  for `colors` would be. The rule of thumb is it's slower than hashmap for insertion and lookup/get but faster for iteration. It's probably worth benchmarking to see what the overhead is vs the current hash map, because a `BTreeMap` will give us a deterministic ordering too.

That being said from a performance perspective the other thing to consider is whether we want to add a custom mapping return type to avoid the copy overhead until access time. If we did this we should stick with a `HashMap` and just document the ordering limitation.

**Comment by ikkoham2** [comment]
Personally, I expect the retworkx's result to be in a fixed order, because the Python dict is ordered. (This does not mean that I want them to be in order from 1..n). networkx also doesn't change the order.
I think it would be better if the results were fixed, since users may also be concerned about reproducibility of the results in their research.

I have checked the `BTreeMap` with the code
```
num_nodes = 10000
num_edges = num_nodes * 10

graph = rx.PyGraph()
graph.add_nodes_from(range(num_nodes))
graph.add_edges_from_no_data([tuple(np.random.randint(0, num_nodes, 2)) for _ in range(num_edges)])
%timeit coloring_dict = rx.graph_greedy_color(graph)
```

It took about 1.5 to 2 times the execution time. 


Now I'm thinking of fixing the `RandomState` of `Hasher`. The default hashing algorithm is slow for this small data and we don't need to worry about HashDOS. I'm still experimenting.

**Comment by IvanIsCoding** [comment]
> Indeed the order of iterating over a hashmap can be arbitary (https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.iter).
> Is an order based on nodes indexes preferred?
> We can easily do this by replacing this loop
> https://github.com/Qiskit/retworkx/blob/010e0de6b8b475843df8aba511fc5731e386fa01/src/lib.rs#L929-L930
> 
> 
> with
> ```rust
> for index in graph.graph.node_indices() {
>         let index = index.index();
>         out_dict.set_item(index, colors[&index])?;
>     }
> ```
> 
> but with a small performance overhead.
> Personally, i would leave it as it is and state this behavior in the documentation.

This is the cleanest change we can do to keep the result deterministic. Also, the overhead of looping through `graph.node_indices()` again is smaller than the overhad of using a `BTree`. If we go forward making the result deterministic, I support sticking with this.

> That being said from a performance perspective the other thing to consider is whether we want to add a custom mapping return type to avoid the copy overhead until access time. If we did this we should stick with a `HashMap` and just document the ordering limitation.

I think this raises an interesting issue: many of our custom types right now are not deterministic becaues of HashMap not being deterministics. Perhaps we should consider looking for alternatives that match the common Python behavior more closely. [indexmap](https://github.com/bluss/indexmap) could be one of those alternatives.

**Comment by ikkoham** [comment]
I tested the following benchmark code:
```python
import timeit

setup = """
import numpy as np

import retworkx as rx

num_nodes = 10000
num_edges = num_nodes * 100

graph = rx.PyGraph()
graph.add_nodes_from(range(num_nodes))
graph.add_edges_from_no_data(
    [tuple(np.random.randint(0, num_nodes, 2)) for _ in range(num_edges)]
)
"""


stmt = "rx.graph_greedy_color(graph)"


if __name__ == "__main__":
    number = 10
    time_list = timeit.repeat(stmt, setup, number=number, repeat=5)
    time_per_func = [t / number for t in time_list]
    print("time list: ", time_per_func)
    print("min_time: ", min(time_per_func))
```

### main (0.9.0)
```python
time list:  [2.2111141039000004, 2.2008289647000003, 2.1712645647000004, 2.203443214399999, 2.204833532800001]
min_time:  2.1712645647000004
```
### Sort (proposed by @georgios-ts )
```diff
-    for (index, color) in colors {
-        out_dict.set_item(index, color)?;
+    for index in graph.graph.node_indices() {
+        let index = index.index();
+        out_dict.set_item(index, colors[&index])?;
```
```python
time list:  [2.1776173052000005, 2.1733322389, 2.2040183676, 2.195622462300001, 2.181998799499999]
min_time:  2.1733322389
```

### fnv_hash #349 
```python
time list:  [2.5385831272, 2.5377669555000004, 2.5374217920999995, 2.5341872295, 2.5315219052000004]
min_time:  2.5315219052000004
```

### Fix RandomState of ahash (proposed by @mtreinish in https://github.com/Qiskit/retworkx/pull/349#issuecomment-854611208)
```python
time list:  [2.1571590641, 2.1814235029000004, 2.1625129248999997, 2.1774825724999998, 2.1685044099999997]
min_time:  2.1571590641
```
### BTreeMap
```python
time list:  [3.9336013793999998, 3.911167955199999, 3.930736628400001, 3.9298833470000005, 3.913138769899999]
min_time:  3.911167955199999
```

**Comment by mtreinish** [comment]
Personally I'm partial to the fixed seed approach, mostly because it's a pattern we can copy in functions with custom return types (where we just move the `HashMap` to a custom rust struct exported as a Python class, for example: https://github.com/Qiskit/retworkx/blob/main/src/lib.rs#L955-L989 ) with minimal effort. Using a sort looks like it would be fine here too there's minimal performance overhead  (I don't think people will notice it) but it only applies to places we actually return `PyDict` and relies on python dict preserving insertion order so it's not a general solution for everywhere we return a mapping.

**Comment by IvanIsCoding** [comment]
> I tested the following benchmark code:
> 
> ```python
> import timeit
> 
> setup = """
> import numpy as np
> 
> import retworkx as rx
> 
> num_nodes = 10000
> num_edges = num_nodes * 100
> 
> graph = rx.PyGraph()
> graph.add_nodes_from(range(num_nodes))
> graph.add_edges_from_no_data(
>     [tuple(np.random.randint(0, num_nodes, 2)) for _ in range(num_edges)]
> )
> """
> 
> 
> stmt = "rx.graph_greedy_color(graph)"
> 
> 
> if __name__ == "__main__":
>     number = 10
>     time_list = timeit.repeat(stmt, setup, number=number, repeat=5)
>     time_per_func = [t / number for t in time_list]
>     print("time list: ", time_per_func)
>     print("min_time: ", min(time_per_func))
> ```

I opted to run this informal benchmark again, and I got:

With main (0.9.0):
```
time list:  [0.44976469549999365, 0.4280503060000001, 0.42795087479998983, 0.4299212453000109, 0.42836694069999337]
min_time:  0.42795087479998983
```

With #386:
```
time list:  [0.4710892716000217, 0.45328074990000006, 0.4626166772000033, 0.46781088539999016, 0.4588312551999934]
min_time:  0.45328074990000006
```
