### ISSUE TITLE
Procedurally weight edges during longest path calculation

### ISSUE THREAD

**Issue by ecpeterson** [Qiskit/retworkx#381]
### What is the expected enhancement?

`dag_longest_path_length` presently does what it says on the tin: it computes the length of the longest chain of edges in the DAG. In applications, we often want to tweak this in two ways:

1. Rather than treating edges uniformly and tallying up their count, we might want to procedurally weight edges according to some user-specified scheme. It's possible to attach this data to the graph object itself, but it can be convenient to supply this to `dag_longest_path_length` itself in some non-persistent way, e.g., as a function.
2. Rather than adding edge weights and taking a maximum at each node to form the running tally, some other combinator might be called for.

As QISKit-motivated examples, we might like to estimate runtime infidelity of a circuit, where each gate incurs some cost (modeled as an edge weight in the `DAGCircuit`) and the errors propagate according to some compounding formula (encoded as a non-max combinator). Even just addressing 1. would be helpful to these ends.

**Comment by mtreinish** [comment]
The simple thing to do here is probably to add a `weight_fn` argument (that defaults to `None` and will act as it does today if not set) to the `dag_longest_path_length` (and by extension `dag_longest_path` as they share a common internal implementation).  For the qiskit use case what I think would be easiest is to just have that `weight_fn` if set get passed a node object (which in terra would be the `DAGNode`) that returns a float weight for the edge from that node in the traversal (as the gate fidelities will be a property of the `op` and the `qubit` both of which are a property of nodes in terra). But, this is a bit contrary to what I would expect as a general graph user since if I was passing a weight callback function I would expect the edge weight to be used, not the node weights. I think the best compromise is to pass the full edge (`source`, `target`, and `weight`) to the callback function and leave it up to the user for what to do.

**Comment by georgios-ts** [comment]
Regarding the second point, do you want an alternative for the sum or the max?
btw, issue title says "shortest path calculation" but you are refering to "longest path" function.

**Comment by ecpeterson** [comment]
Both! Rather than adding up steps in a path, I might instead want to multiply some fidelities; and rather than picking the worst value over all ancestor nodes, I might want to form some amalgam (e.g., a product of ancestor fidelities).

I should say again, though, that we can make do with a lot less — just edge weights, as in Matthew's `weight_fn`, would already be very useful. So, whatever's convenient to provide on retworkx's end.
