### ISSUE TITLE
Make a graph from an adjacency matrix with negative elements

### ISSUE THREAD

**Issue by k-tamuraphys** [Qiskit/retworkx#408]
### Information

- **retworkx version**:0.9.0
- **Python version**:3.9.6
- **Operating system**:macOS Big Sur 11.4

### What is the current behavior?
When I tried to make a graph from an adjacency matrix with negative matrix elements, I noticed that edges corresponding to the negative elements are neglected.

When the adjacency matrix is as follows,
```python
adjacency_matrix = np.array([
    [1.0, -1.0, 2.0], 
    [0.0, 1.0, 1.0], 
    [0.0, 0.0, 1.0]
])
```
then the list of weighted edges,
```python
graph = retworkx.PyGraph.from_adjacency_matrix(adjacency_matrix)
list(graph.weighted_edge_list())
```
outputs,
```python
[(0, 0, 1.0), (0, 2, 2.0), (1, 1, 1.0), (1, 2, 1.0), (2, 2, 1.0)]
```
It means that there is no edge between node 0 and 1. 

On the other hand, if the adjacency matrix is 

```python
adjacency_matrix = np.array([
    [1.0, 1.0, 2.0], 
    [0.0, 1.0, 1.0], 
    [0.0, 0.0, 1.0]
])

graph = retworkx.PyGraph.from_adjacency_matrix(adjacency_matrix)
list(graph.weighted_edge_list())
```
then the list of weighted edges is like this:
```python
[(0, 0, 1.0), (0, 1, 1.0), (0, 2, 2.0), (1, 1, 1.0), (1, 2, 1.0), (2, 2, 1.0)]
```

### What is the expected behavior?
Is the above behavior is a bug or intended?
If it is a bug, I expect that negative elements of a given adjacency matrix are not neglected.
For example, for the adjacency matrix
```python
adjacency_matrix = np.array([
    [1.0, -1.0, 2.0], 
    [0.0, 1.0, 1.0], 
    [0.0, 0.0, 1.0]
])
```
I want the following list of weighted edges:
```python
[(0, 0, 1.0), (0, 1, -1.0), (0, 2, 2.0), (1, 1, 1.0), (1, 2, 1.0), (2, 2, 1.0)]
```
Furthermore, it would be more convenient if we can create a graph from an adjacency matrix with complex matrix elements as follows.
```python
adjacency_matrix = np.array([
    [1.0, 1.0+1.0j, 2.0+2.0j], 
    [0.0, 2.0, 3.0+3.0j], 
    [0.0, 0.0, 3.0]
])
graph = retworkx.PyGraph.from_adjacency_matrix(adjacency_matrix)
list(graph.weighted_edge_list())
```
```python
[(0, 0, 1.0), (0, 1, 1.0+1.0j), (0, 2, 2.0+2.0), (1, 1, 2.0), (1, 2, 3.0+3.0j), (2, 2, 3.0)]
```

### Steps to reproduce the problem
```python
adjacency_matrix = np.array([
    [1.0, -1.0, 2.0], 
    [0.0, 1.0, 1.0], 
    [0.0, 0.0, 1.0]
])
graph = retworkx.PyGraph.from_adjacency_matrix(adjacency_matrix)
list(graph.weighted_edge_list())
```

**Comment by mtreinish** [comment]
I expect this is an oversight and can be fixed by changing this line: https://github.com/Qiskit/retworkx/blob/main/src/graph.rs#L1405 to be `!= 0`. That should still work as expected but handle negative weights. It might also be worth adding a kwarg at the same time to adjust the null value so it can be `inf` or `nan` instead of zero.

As for the complex element array that's a bit trickier, the method is statically typed as it uses numpy's c api to read the array and we are prevented from using generics by pyo3 when building the interface to python (it needs to know the type to build the interface function). The best we could probably do is add a second method like `from_complex_adjacency_matrix` or something. Would that work for your use case?
