### ISSUE TITLE
[joss] How to find connected components in undirected graphs?

### ISSUE THREAD

**Issue by szhorvat** [Qiskit/retworkx#514]
How can I find the connected components in an undirected graph?

For directed graphs, there are `retworkx.strongly_connected_components` and `retworkx.weakly_connected_components`, but these throw an error on undirected graphs. 

This is one of the most fundamental operations so I expect there must be a function that I'm just missing?

**Comment by georgios-ts** [comment]
No, currently such function is missing for undirected graphs but it should be a simple addition.
In general, `PyDiGraph` has received more attention due to its extensive use in qiskit-terra, so there might be some functionality gaps between undirected/directed graphs that we should definitely start closing.
