### ISSUE TITLE
Loading graphml fails if there are any graph attributes

### ISSUE THREAD

**Issue by PadenZach** [Qiskit/retworkx#607]
### Information

- **retworkx version**:
- Built from source.
- **Python version**:
- 3.10
- **Rust version**:
- 1.60
- **Operating system**:
- Ubuntu 20.04 on WSL2

### What is the current behavior?
Loading graphml with graph attributes results in error.
EG:
rx_graph = rx.read_graphml("manhatten.graphml")
yields:
"Exception: Unsupported 'for' attribute in key with id=d2."

Going into my graphML file, thie seems to be caused by this line:
` <key attr.name="streets_per_node" attr.type="string" for="graph" id="d2" />`
Removing this line, and other lines that contain `for="graph"` allow me to load the graphml file.

### What is the expected behavior?
I guess this could be broken down to do different things.

a) A bug fix to just ignore graph attributes (or warn) if they're not supported.
b) Support the loading of graph-level attributes (This would be feature-parity with networkx).

### Steps to reproduce the problem
Attempt to load the graphml available here:
https://www.kaggle.com/datasets/crailtap/street-network-of-new-york-in-graphml

You should see that the graph attributes are causing this error. Please let me know if you'd like me to post a more in depth series of steps to reproduce the error.

**Comment by mtreinish** [comment]
Thanks for testing the graphml parser, heh it only merged a couple of days ago. :) Yeah, that's a fair point, it raises an unsupported error now because there is no concept of graph level attributes for retworkx graphs currently. We've avoided adding a concept of attributes in retworkx so far primarily because nodes and edges allow any python object data payload so having separate attributes on those is not fully necessary. But for graph attributes there is no equivalent alternative besides subclassing and adding an extra field or wrapping a graph in a larger data structure.

I think instead of downgrading the unsupported feature error to a warning it would be better to just add an attributes parameter to the retworkx graph classes and then updating the new graphml parser to populate that with a dict if the graphml has attributes defined.

**Comment by mtreinish** [comment]
To start, I added graph attributes to the retworkx graph classes in #608. After that merges we can update the graphml parser to populate the new attribute on the object. Since the attribute by itself was a large enough and self contained change I opted to do that in a standalone PR and save the PR for updating the graphml parser (which we'll tag as closing this issue) to leverage that after it merges.
