### ISSUE TITLE
Missing function find_negative_cycle, negative_edge_cycle

### ISSUE THREAD

**Issue by chikko80** [Qiskit/retworkx#620]
### Information

- **retworkx version**: 0.12.0
- **Python version**: 3.9.13

### What is the current behavior?
Regarding #603 the functions

   - find_negative_cycle
   - negative_edge_cycle

should be callable from python.
I can't call them, nor do I find them in the __init__.py.

### What is the expected behavior?
Functions should be callable from python

### Steps to reproduce the problem
try to call
`retworkx. find_negative_cycle()`

maybe I am just too dumb to use the library, then I am sorry
hopefully someone can enlighten me

**Comment by georgios-ts** [comment]
These functions will be included in the next release. For now you can use them if you install retworkx from the main branch.

**Comment by chikko80** [comment]
@georgios-ts 
i've installed the lib from the main branch, but the function isn't implemented there, check the __init__.py in retworkx directory

**Comment by georgios-ts** [comment]
Do you have local clone of retworkx repository? If so, can you confirm that it's up to date with retworkx main branch and then `pip install .` ?

**Comment by chikko80** [comment]
yes, i have a local clone and I am on version 0.12.0 but neither i can't see the functions, nor i can call them
can't you reproduce it?

**Comment by mtreinish** [comment]
The 2 functions in question exist solely in the rust code and do not have shims in `__init__.py` (because they only work with one type there is no need for python dispatch). If you've installed from source and python is not able to find the function the most likely reason is that you're running from the repository root directory (or somewhere else with a `retworkx` directory). As the last paragraph in the building from source docs say: https://github.com/Qiskit/retworkx#building-from-source

```
There are 2 things to note when doing this though, first if you try to run python from the repo root using this method it will not work as you expect. There is a name conflict in the repo root because of the local python package shim used in building the package. Simply run your python scripts or programs using retworkx outside of the repo root. 
```

In those cases Python is "helpfully" trying to use the local source tree instead of the package you built and installed with the same name, but the local source tree does not have the compiled library file which is why the function cannot be found. There are two ways to fix this either change directories or build the extension in place. Changing directories is easier and maintains the isolation of the installed package and the source tree. But, if you want to build it in place you can do `python setup.py build_rust --release --inplace` and that will recompile the rust portion of the library and copy the library file to the local retworkx directory.

**Comment by chikko80** [comment]
I solved it, it was a caching problem with pipenv

**Comment by mtreinish** [comment]
Cool, glad you were able to get to the bottom of your issue.
